name: deblur
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.21.0
  - matplotlib>=3.3.0
  - tqdm>=4.62.0
  - tensorboard>=2.7.0
  - requests>=2.25.0
  - pip
  - pip:
    - opencv-python>=4.5.0
    - Pillow>=8.3.0
    - scikit-image>=0.18.0
    - albumentations>=1.3.0
    - huggingface-hub>=0.16.0
    - datasets>=2.0.0